services:
  kittysaver:
    image: kittysaver
    build:
      context: .
      dockerfile: KittySaver/Dockerfile

  kittysaver.auth.api:
    image: kittysaver.auth.api
    build:
      context: .
      dockerfile: KittySaver.Auth.Api/Dockerfile

  kittysaver.api:
    image: kittysaver.api
    build:
      context: .
      dockerfile: src/KittySaver.Api/Dockerfile
