services:
  kittysaver:
    image: kittysaver
    build:
      context: .
      dockerfile: KittySaver/Dockerfile

  kittysaver.auth.api:
    image: kittysaver.auth.api
    build:
      context: .
      dockerfile: KittySaver.Auth.Api/Dockerfile
