namespace KittySaver.Api.Shared.Persistence.ReadModels;

public sealed record PersonReadModel(
    Guid Id,
    string CreatedBy,
    DateTimeOffset CreatedOn,
    string? LastModificationBy,
    DateTimeOffset? LastModificationOn,
    ICollection<CatReadModel> Cats,
    ICollection<AdvertisementReadModel> Advertisements,
    int CurrentRole,
    Guid UserIdentityId,
    string DefaultAdvertisementsContactInfoEmail,
    string DefaultAdvertisementsContactInfoPhoneNumber,
    string DefaultAdvertisementsPickupAddressBuildingNumber,
    string DefaultAdvertisementsPickupAddressCity,
    string DefaultAdvertisementsPickupAddressCountry,
    string? DefaultAdvertisementsPickupAddressState,
    string DefaultAdvertisementsPickupAddressStreet,
    string DefaultAdvertisementsPickupAddressZipCode,
    string Email,
    string FirstName,
    string LastName,
    string PhoneNumber,
    string ResidentalAddressBuildingNumber,
    string ResidentalAddressCity,
    string ResidentalAddressCountry,
    string? ResidentalAddressState,
    string ResidentalAddressStreet,
    string ResidentalAddressZipCode
);